version: "3.9"

services:
  # Frontend - Angular App
  web:
    build: 
      context: .
      dockerfile: Dockerfile.local
    image: banking-portal:local
    ports:
      - "4200:4200"
    environment:
      - BACKEND_URL=http://host.docker.internal:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - banking-network

  # Backend - Puedes descomentar esto si quieres levantar el backend tambi√©n
  # backend:
  #   image: client-core-service:latest
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - banking-network

networks:
  banking-network:
    driver: bridge
